name: Build unlocker.exe

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile with MSVC
        shell: cmd
        run: cl /EHsc /Fe:unlocker.exe src\main.cpp
        working-directory: ${{ github.workspace }}

      - name: List files after linking
        shell: cmd
        run: dir /s /b
        working-directory: ${{ github.workspace }}

      - name: Upload unlocker.exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: unlocker-exe
          path: '**/unlocker.exe'
