name: Build unlocker.exe

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List all project files (PowerShell)
      run: Get-ChildItem -Recurse -File | Select-Object FullName

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile unlocker.exe
      run: cl /EHsc /Fe:unlocker.exe src/main.cpp

    - name: Upload .exe
      uses: actions/upload-artifact@v4
      with:
        name: unlocker-exe
        path: unlocker.exe
