name: Build unlocker.exe

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show files (for debugging)
      run: dir /s /b

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build unlocker.exe
      run: cl /EHsc /Fe:unlocker.exe src\main.cpp

    - name: Upload .exe
      uses: actions/upload-artifact@v4
      with:
        name: unlocker-exe
        path: unlocker.exe
